# TODO: update with new padring and IHP130

[chipflow]
project_id = 12

[chipflow.steps]
sim = "my_design.steps.sim:MySimStep"
board = "my_design.steps.board:MyBoardStep"
silicon = "my_design.steps.silicon:MySiliconStep"
software = "my_design.steps.software:MySoftwareStep"
export = "my_design.steps.export_verilog:ExportVerilogStep"

[chipflow.silicon]
process = "ihp_sg13g2"
pad_ring = "pga144"

[chipflow.silicon.pads]

# QSPI flash
flash_clk = { type = "o",  loc = "2" }
flash_csn = { type = "o",  loc = "3" }
flash_d0  = { type = "io",  loc = "4" }
flash_d1  = { type = "io",  loc = "5" }
flash_d2  = { type = "io",  loc = "6" }
flash_d3  = { type = "io",  loc = "7" }

# spare x3

# I2C 0
i2c0_scl = { type = "io", loc = "26" }
i2c0_sda = { type = "io", loc = "27" }

# x 6 reserved analog input

# UART 0
uart0_rx = {type = "i", loc = "78" }
uart0_tx = {type = "o", loc = "79" }

# x1 reserved

# Scan chain JTAG
sc_jtag_tck  = { type = "i", loc = "107" }
sc_jtag_tms  = { type = "i", loc = "108" }
sc_jtag_tdi  = { type = "i", loc = "109" }
sc_jtag_tdo  = { type = "o", loc = "110" }
sc_jtag_trst = { type = "i", loc = "111" }

# x1 reserved

# System
sys_clk   = { type = "i", loc = "114" }
sys_rst_n = { type = "i", loc = "115" }
test_clk  = { type = "i", loc = "116" }
test_mode = { type = "i", loc = "117" }
heartbeat = { type = "o", loc = "118" }

# x17 reserved (T1S PHY)

# x2 reserved (SENT angle sensors)

[chipflow.silicon.power]
dvss0        = { loc =   "1" }
dvdd0        = { loc =   "9" }
vss0         = { loc =  "17" }
vdd0         = { loc =  "25" }
dvss1        = { loc =  "33" }
dvdd1        = { loc =  "41" }
vss1         = { loc =  "49" }
vdd1         = { loc =  "57" }
dvss2        = { loc =  "65" }
dvdd2        = { loc =  "73" }
vss2         = { loc =  "81" }
vdd2         = { loc =  "89" }
dvss3        = { loc =  "97" }
dvdd3        = { loc = "105" }
vss3         = { loc = "113" }
vdd3         = { loc = "121" }
dvss4        = { loc = "129" }
dvdd4        = { loc = "137" }
