[chipflow]
project_name = "chipflow-examples-minimal"

[chipflow.top]
soc = "design.design:MySoC"

[chipflow.steps]
board = "design.steps.board:MyBoardStep"

[chipflow.silicon]
process = "sky130"
package = "openframe"

[chipflow.test]
event_reference = "design/tests/events_reference.json"
