[chipflow]
project_name = "chipflow-examples-minimal"

[chipflow.top]
soc = "design.design:MySoC"

[chipflow.steps]
software = "design.steps.software:MySoftwareStep"

[chipflow.silicon]
process = "ihp_sg13g2"
package = "pga144"

[chipflow.power.domains]
core_io.voltage = '3.3v'
core_io.type = 'IO'
rs485.voltage = '5v'
rs485.type = 'IO'

[chipflow.power]
uart0.io = 'rs485'


